// Generated by scripts/inline-sources.ts — do not edit by hand.
import type { DemoMeta } from "./types";

export const GENERATED_META: Record<string, DemoMeta> = {
  ceramic: {
    title: "Ceramic Keys",
    description:
      "Glazed-clay keycaps and a kiln-fired toggle — speckled glaze, soft studio shadows, and a spring press that physically depresses each key.",
    category: "materials",
    tags: ["clay", "tactile"],
    packages: ["@vectojs/core"],
    order: 20,
  },
  "glitch-text": {
    title: "Glitch Text",
    description:
      "Headline type that tears into misregistered print plates — coral/teal channel splits, sliced scanbands, and dropout blocks in timed bursts.",
    category: "effects",
    tags: ["type", "distortion"],
    packages: ["@vectojs/core"],
    order: 10,
  },
  jelly: {
    title: "Jelly Buttons",
    description:
      "Wobbling gelatin blobs on a mass-spring rim — poke one and the whole surface ripples; hit-testing follows the deformed outline, not a box.",
    category: "materials",
    tags: ["spring", "squishy"],
    packages: ["@vectojs/core"],
    order: 30,
  },
  "liquid-glass": {
    title: "Liquid Glass",
    description:
      "A draggable frosted-glass card that refracts a drifting color field behind it — live backdrop sampling, edge bending, and a spring-lagged grab.",
    category: "materials",
    tags: ["glass", "refraction"],
    packages: ["@vectojs/core"],
    order: 10,
  },
};
