// Generated by scripts/inline-sources.ts — do not edit by hand.
import type { DemoMeta } from './types';

export const GENERATED_META: Record<string, DemoMeta> = {
  ceramic: {
    title: 'Ceramic Keys',
    description:
      'Glazed-clay keycaps and a kiln-fired toggle — speckled glaze, soft studio shadows, and a spring press that physically depresses each key.',
    category: 'materials',
    tags: ['clay', 'tactile'],
    packages: ['@vectojs/core'],
    order: 20,
  },
  'glitch-text': {
    title: 'Glitch Text',
    description:
      'Headline type that tears into misregistered print plates — coral/teal channel splits, sliced scanbands, and dropout blocks in timed bursts.',
    category: 'effects',
    tags: ['type', 'distortion'],
    packages: ['@vectojs/core'],
    order: 10,
  },
  jelly: {
    title: 'Jelly Buttons',
    description:
      'Wobbling gelatin blobs on a mass-spring rim — poke one and the whole surface ripples; hit-testing follows the deformed outline, not a box.',
    category: 'materials',
    tags: ['spring', 'squishy'],
    packages: ['@vectojs/core'],
    order: 30,
  },
  'liquid-glass': {
    title: 'Liquid Glass',
    description:
      'A draggable frosted-glass card that refracts a drifting color field behind it — live backdrop sampling, edge bending, and a spring-lagged grab.',
    category: 'materials',
    tags: ['glass', 'refraction'],
    packages: ['@vectojs/core'],
    order: 10,
  },
  'constellation-lines': {
    title: 'Constellation Lines',
    description:
      'Drifting points connect to nearby neighbors with distance-faded links — a live, switchable comparison of SpatialHashGrid neighbor queries against a naive O(n²) search, with real measured query time on screen.',
    category: 'effects',
    tags: ['particles', 'spatial-index', 'webgl'],
    packages: ['@vectojs/core'],
    order: 20,
  },
  'particle-text': {
    title: 'Particle Text',
    description:
      'Type any two words and Transform scatters the first into a particle cloud that reforms as the second — spring-to-origin physics (ComputeParticleEntity) holds each shape together. Adjustable particle count, transform duration, and a two-stop gradient (built from several color-tinted particle buckets). The real text stays reachable through Ctrl+F and screen readers the whole time via a separate, unselectable content-projection host.',
    category: 'effects',
    tags: ['particles', 'webgpu', 'content-projection'],
    packages: ['@vectojs/core'],
    order: 30,
  },
  'mercury-blobs': {
    title: 'Mercury Blobs',
    description:
      "Draggable silvery blobs that merge into one liquid surface when close and split apart when pulled away — a classic blur + contrast-ramp 'goo' composite, with the drag hit-testing following each blob's own circle regardless of how merged it currently looks.",
    category: 'materials',
    tags: ['goo', 'metaball', 'drag'],
    packages: ['@vectojs/core'],
    order: 40,
  },
  'ripple-text': {
    title: 'Ripple Text',
    description:
      'Sine-wave text distortion with animated color gradient — characters undulate like a flag in wind',
    category: 'effects',
    tags: ['text', 'wave', 'gradient'],
    packages: ['@vectojs/core'],
    order: 40,
  },
  'particle-morph': {
    title: 'Particle Morph',
    description:
      'Hundreds of particles automatically cycling between geometric shapes — circle, star, hexagon, diamond, heart',
    category: 'effects',
    tags: ['particles', 'morph', 'shapes', 'webgpu'],
    packages: ['@vectojs/core'],
    order: 50,
  },
  'glow-bloom': {
    title: 'Glow Bloom',
    description:
      'Post-processing bloom effect — bright shapes bloom and bleed light into surrounding space with adjustable spread and intensity',
    category: 'effects',
    tags: ['bloom', 'glow', 'post-processing'],
    packages: ['@vectojs/core'],
    order: 60,
  },
  'frosted-glass': {
    title: 'Frosted Glass',
    description:
      'Draggable frosted-glass panels with adjustable blur, grain texture, and tilt — a translucent, etched-surface alternative to liquid glass',
    category: 'materials',
    tags: ['glass', 'frost', 'blur', 'grain'],
    packages: ['@vectojs/core'],
    order: 50,
  },
};
