import type { Demo } from "./types";
import { GENERATED_SOURCES } from "./generated-sources";
// Generated by scripts/inline-sources.ts alongside GENERATED_SOURCES — every
// demo's own src/demos/<id>/meta.ts, collected at build time. One file per
// demo means adding a demo never edits a file another demo's PR also
// touches, so parallel additions cannot merge-conflict on this data.
import { GENERATED_META } from "./generated-meta";

export type { Demo, DemoCategory, DemoMeta } from "./types";
export { CATEGORIES } from "./types";

export const DEMOS: Demo[] = Object.entries(GENERATED_META)
  .map(([id, meta]) => ({
    id,
    ...meta,
    moduleSource: GENERATED_SOURCES[id]?.moduleSource ?? "",
    htmlSource: GENERATED_SOURCES[id]?.htmlSource ?? "",
  }))
  .sort((a, b) => a.order - b.order || a.id.localeCompare(b.id));
