import { readdirSync, readFileSync, existsSync, writeFileSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

export interface DemoSources {
  moduleSource: string;
  htmlSource: string;
}

/**
 * Read every `<demosRoot>/<id>/{demo.js,index.html}` pair and return the raw
 * file text keyed by demo id. Directories missing either file are skipped, so
 * a half-authored demo never emits partial sources. Raw bytes are preserved
 * verbatim so the shown code equals the code that runs in the iframe.
 */
export function collectSources(demosRoot: string): Record<string, DemoSources> {
  const out: Record<string, DemoSources> = {};
  if (!existsSync(demosRoot)) return out;
  for (const entry of readdirSync(demosRoot, { withFileTypes: true })) {
    if (!entry.isDirectory()) continue;
    const dir = join(demosRoot, entry.name);
    const modulePath = join(dir, "demo.js");
    const htmlPath = join(dir, "index.html");
    if (!existsSync(modulePath) || !existsSync(htmlPath)) continue;
    out[entry.name] = {
      moduleSource: readFileSync(modulePath, "utf8"),
      htmlSource: readFileSync(htmlPath, "utf8"),
    };
  }
  return out;
}

function renderModule(map: Record<string, DemoSources>): string {
  return (
    "// Generated by scripts/inline-sources.ts — do not edit by hand.\n" +
    'import type { DemoSources } from "../../scripts/inline-sources";\n\n' +
    "export const GENERATED_SOURCES: Record<string, DemoSources> = " +
    JSON.stringify(map, null, 2) +
    ";\n"
  );
}

function main(): void {
  const here = dirname(fileURLToPath(import.meta.url));
  const demosRoot = join(here, "..", "src", "demos");
  const outPath = join(here, "..", "src", "registry", "generated-sources.ts");
  const map = collectSources(demosRoot);
  writeFileSync(outPath, renderModule(map));
  console.log(
    `inline-sources: wrote ${Object.keys(map).length} demo source(s) to ${outPath}`,
  );
}

if (import.meta.main) main();
