import {
  readdirSync,
  readFileSync,
  existsSync,
  writeFileSync,
  mkdirSync,
  cpSync,
  rmSync,
} from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

export interface DemoSources {
  moduleSource: string;
  htmlSource: string;
}

/**
 * Read every `<demosRoot>/<id>/{demo.js,index.html}` pair and return the raw
 * file text keyed by demo id. Directories missing either file are skipped, so
 * a half-authored demo never emits partial sources. Raw bytes are preserved
 * verbatim so the shown code equals the code that runs in the iframe.
 */
export function collectSources(demosRoot: string): Record<string, DemoSources> {
  const out: Record<string, DemoSources> = {};
  if (!existsSync(demosRoot)) return out;
  for (const entry of readdirSync(demosRoot, { withFileTypes: true })) {
    if (!entry.isDirectory()) continue;
    const dir = join(demosRoot, entry.name);
    const modulePath = join(dir, "demo.js");
    const htmlPath = join(dir, "index.html");
    if (!existsSync(modulePath) || !existsSync(htmlPath)) continue;
    out[entry.name] = {
      moduleSource: readFileSync(modulePath, "utf8"),
      htmlSource: readFileSync(htmlPath, "utf8"),
    };
  }
  return out;
}

function renderModule(map: Record<string, DemoSources>): string {
  return (
    "// Generated by scripts/inline-sources.ts — do not edit by hand.\n" +
    'import type { DemoSources } from "../../scripts/inline-sources";\n\n' +
    "export const GENERATED_SOURCES: Record<string, DemoSources> = " +
    JSON.stringify(map, null, 2) +
    ";\n"
  );
}

/**
 * Mirror each authored demo dir into `public/demos/<id>/` so it is served as a
 * real static route (`/demos/<id>/`) with a genuine document URL. This is what
 * the sandboxed iframe loads via `src` — a `srcdoc` iframe has base URL
 * `about:srcdoc`, so the demo's `./demo.js` and `/no-ff-webgpu.js` script refs
 * can't resolve there. `src/demos/` stays the single committed source of truth;
 * `public/demos/` is generated (gitignored) and rebuilt from scratch each run.
 */
function copyDemosToPublic(demosRoot: string, publicDemos: string): number {
  rmSync(publicDemos, { recursive: true, force: true });
  if (!existsSync(demosRoot)) return 0;
  let n = 0;
  for (const entry of readdirSync(demosRoot, { withFileTypes: true })) {
    if (!entry.isDirectory()) continue;
    const dir = join(demosRoot, entry.name);
    if (
      !existsSync(join(dir, "demo.js")) ||
      !existsSync(join(dir, "index.html"))
    )
      continue;
    mkdirSync(join(publicDemos, entry.name), { recursive: true });
    cpSync(dir, join(publicDemos, entry.name), { recursive: true });
    n++;
  }
  return n;
}

function main(): void {
  const here = dirname(fileURLToPath(import.meta.url));
  const demosRoot = join(here, "..", "src", "demos");
  const outPath = join(here, "..", "src", "registry", "generated-sources.ts");
  const map = collectSources(demosRoot);
  writeFileSync(outPath, renderModule(map));
  const copied = copyDemosToPublic(
    demosRoot,
    join(here, "..", "public", "demos"),
  );
  console.log(
    `inline-sources: wrote ${Object.keys(map).length} demo source(s) to ${outPath}; mirrored ${copied} demo dir(s) to public/demos/`,
  );
}

if (import.meta.main) main();
