import {
  readdirSync,
  readFileSync,
  existsSync,
  writeFileSync,
  mkdirSync,
  cpSync,
  rmSync,
} from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';
import { execFileSync } from 'node:child_process';
import type { DemoMeta } from '../src/registry/types';

export interface DemoSources {
  moduleSource: string;
  htmlSource: string;
}

/**
 * Read every `<demosRoot>/<id>/{demo.ts,index.html}` pair and return the raw
 * file text keyed by demo id. Directories missing either file are skipped, so
 * a half-authored demo never emits partial sources. `moduleSource` holds the
 * AUTHORED TypeScript — the better reading reference, and what the code panel
 * shows — not the compiled JS that `copyDemosToPublic` actually serves. See
 * AGENTS.md's "code shown = code authored; code served = its compiled
 * output" note.
 */
export function collectSources(demosRoot: string): Record<string, DemoSources> {
  const out: Record<string, DemoSources> = {};
  if (!existsSync(demosRoot)) return out;
  for (const entry of readdirSync(demosRoot, { withFileTypes: true })) {
    if (!entry.isDirectory()) continue;
    const dir = join(demosRoot, entry.name);
    const modulePath = join(dir, 'demo.ts');
    const htmlPath = join(dir, 'index.html');
    if (!existsSync(modulePath) || !existsSync(htmlPath)) continue;
    out[entry.name] = {
      moduleSource: readFileSync(modulePath, 'utf8'),
      htmlSource: readFileSync(htmlPath, 'utf8'),
    };
  }
  return out;
}

/**
 * Dynamically import every `<demosRoot>/<id>/meta.ts` (one file per demo —
 * see registry/types.ts DemoMeta doc) and return the default export keyed by
 * demo id. Bun evaluates the .ts import directly, no separate compile step.
 */
export async function collectMeta(demosRoot: string): Promise<Record<string, DemoMeta>> {
  const out: Record<string, DemoMeta> = {};
  if (!existsSync(demosRoot)) return out;
  for (const entry of readdirSync(demosRoot, { withFileTypes: true })) {
    if (!entry.isDirectory()) continue;
    const metaPath = join(demosRoot, entry.name, 'meta.ts');
    if (!existsSync(metaPath)) continue;
    const mod = (await import(pathToFileURL(metaPath).href)) as {
      default: DemoMeta;
    };
    out[entry.name] = mod.default;
  }
  return out;
}

function renderSourcesModule(map: Record<string, DemoSources>): string {
  return (
    '// Generated by scripts/inline-sources.ts — do not edit by hand.\n' +
    'import type { DemoSources } from "../../scripts/inline-sources";\n\n' +
    'export const GENERATED_SOURCES: Record<string, DemoSources> = ' +
    JSON.stringify(map, null, 2) +
    ';\n'
  );
}

function renderMetaModule(map: Record<string, DemoMeta>): string {
  return (
    '// Generated by scripts/inline-sources.ts — do not edit by hand.\n' +
    'import type { DemoMeta } from "./types";\n\n' +
    'export const GENERATED_META: Record<string, DemoMeta> = ' +
    JSON.stringify(map, null, 2) +
    ';\n'
  );
}

/**
 * Compile one authored `demo.ts` to plain `demo.js` in `destDir`, preserving
 * comments — the demos carry load-bearing explanatory comments (physics
 * rationale, engine-trap warnings), so a comment-stripping transpiler is the
 * wrong tool even though it's the more obvious one:
 *
 * - `Bun.Transpiler`/`bun build` both strip every comment unconditionally in
 *   bundling mode, with no flag to keep them.
 * - `tsc --removeComments false`, run per-file (NOT via `-p tsconfig.json`,
 *   which would bundle nothing but does pull in the workspace's ambient
 *   types), preserves them verbatim while still erasing all type syntax.
 *   `--ignoreConfig` silences the otherwise-fatal TS5112 caused by the
 *   tsconfig.json sitting in this same working directory.
 *
 * Each file compiles standalone, not bundled, so a bare `@vectojs/*`
 * specifier in the source passes through untouched for the browser's own
 * importmap to resolve — exactly what index.html already declares.
 */
function compileDemoModule(srcPath: string, destDir: string): void {
  execFileSync('tsc', [
    srcPath,
    '--outDir',
    destDir,
    '--module',
    'esnext',
    '--target',
    'esnext',
    '--moduleResolution',
    'bundler',
    '--removeComments',
    'false',
    '--ignoreConfig',
  ]);
  // tsc's own output is not house-formatted; oxfmt --write below (in main())
  // normalizes it before it ever ships, matching every other generated file.
}

/**
 * Mirror each authored demo dir into `public/demos/<id>/` so it is served as a
 * real static route (`/demos/<id>/`) with a genuine document URL. This is what
 * the sandboxed iframe loads via `src` — a `srcdoc` iframe has base URL
 * `about:srcdoc`, so the demo's `./demo.js` and `/no-ff-webgpu.js` script refs
 * can't resolve there. `src/demos/` stays the single committed source of truth;
 * `public/demos/` is generated (gitignored) and rebuilt from scratch each run.
 *
 * `demo.ts` compiles to `demo.js` (see {@link compileDemoModule}); `index.html`
 * copies verbatim, since it already references the served filename `./demo.js`
 * and needs no changes. `meta.ts` is authoring-only and excluded either way.
 */
function copyDemosToPublic(demosRoot: string, publicDemos: string): number {
  rmSync(publicDemos, { recursive: true, force: true });
  if (!existsSync(demosRoot)) return 0;
  let n = 0;
  const compiledJsFiles: string[] = [];
  for (const entry of readdirSync(demosRoot, { withFileTypes: true })) {
    if (!entry.isDirectory()) continue;
    const dir = join(demosRoot, entry.name);
    const modulePath = join(dir, 'demo.ts');
    const htmlPath = join(dir, 'index.html');
    if (!existsSync(modulePath) || !existsSync(htmlPath)) continue;
    const destDir = join(publicDemos, entry.name);
    mkdirSync(destDir, { recursive: true });
    cpSync(htmlPath, join(destDir, 'index.html'));
    compileDemoModule(modulePath, destDir);
    compiledJsFiles.push(join(destDir, 'demo.js'));
    n++;
  }
  // One oxfmt pass over every compiled demo.js: tsc's own output uses double
  // quotes and unwrapped lines, so this is what makes the served file match
  // house style rather than reading as machine-generated in a diff/devtools.
  if (compiledJsFiles.length > 0) execFileSync('oxfmt', ['--write', ...compiledJsFiles]);
  return n;
}

async function main(): Promise<void> {
  const here = dirname(fileURLToPath(import.meta.url));
  const demosRoot = join(here, '..', 'src', 'demos');
  const registryDir = join(here, '..', 'src', 'registry');
  const sources = collectSources(demosRoot);
  writeFileSync(join(registryDir, 'generated-sources.ts'), renderSourcesModule(sources));
  const meta = await collectMeta(demosRoot);
  const metaPath = join(registryDir, 'generated-meta.ts');
  writeFileSync(metaPath, renderMetaModule(meta));
  const sourcesPath = join(registryDir, 'generated-sources.ts');
  // Format with the repo's own formatter, because these two files are
  // committed and `format:check` covers them. That formatter is oxfmt, not
  // prettier: this line used to shell out to prettier, which left both files
  // failing oxfmt --check the moment they were regenerated, so a working tree
  // went dirty just from running this script. prettier is also not a declared
  // dependency — it only resolved transitively via prettier-plugin-astro.
  // Both files need it: JSON.stringify nests meta's arrays/objects, and
  // generated-sources.ts holds long escaped string literals oxfmt re-wraps.
  execFileSync('oxfmt', ['--write', metaPath, sourcesPath]);
  const copied = copyDemosToPublic(demosRoot, join(here, '..', 'public', 'demos'));
  console.log(
    `inline-sources: wrote ${Object.keys(sources).length} demo source(s) + ${Object.keys(meta).length} meta entr(y/ies); mirrored ${copied} demo dir(s) to public/demos/`,
  );
}

if (import.meta.main) void main();
